### ISSUE TITLE
Error: Failed to load shared library: 找不到指定的模块。

### ISSUE THREAD

**Issue by skywalker07** [hargup/reader#1]
![1](https://github.com/user-attachments/assets/e7d7fcfb-a369-4b90-b18a-a39e24b7c2ee)

**Comment by hargup** [comment]
@skywalker07 did the solution suggested here worked for you? https://github.com/jina-ai/reader/issues/3#issuecomment-2357423817 

I'm not able to reproduce the issue locally.
