### ISSUE TITLE
INFO: Page 1: Scraping http://favicon.ico/ { url: 'http://favicon.ico/' } D:\code\jina-reader-hargup\reader\backend\functions\node_modules\tld-extract\index.js:43       throw new Error("Invalid TLD " + JSON.stringify({parts, tld_level, allowUnknownTLD}));

### ISSUE THREAD

**Issue by skywalker07** [hargup/reader#2]
the following error occurred when crawling：
![1](https://github.com/user-attachments/assets/5fa2d789-29f9-4c0d-87e2-463c09983e64)

**Comment by IT-Xue** [comment]
i got the same error, Can you tell me how you solved this problem?

**Comment by IT-Xue** [comment]
I got the reason.
This error occurs in the Chrome browser and no problem in the curl code. 
Maybe the wrong header of  browser request cause the error
